@startuml navigation
skinparam minClassWidth 100
skinparam classBackgroundColor WhiteSmoke
skinparam classBorderColor DarkSlateGrey
hide members
hide circles

class index
class signup
class search
class add_pet_posting
class list_pet_postings
class show_pet_posting
class profile
class action_login
class action_logout
class action_signup
class action_search
class action_add_pet_posting

index -[#black]down-> signup
index -[#black]> action_login
index-[#black]down->profile
action_login -[#black]> index
signup-[#black]right>action_signup
action_signup..up[#green]>index
action_signup..[#red]>signup
index-[#black]left>action_logout
action_logout-[#black]>index
index--[#black]up>search
search-left[#black]>action_search
action_search.[#red]>search
action_search....[#green]>list_pet_postings
index -left[#black]->add_pet_posting
add_pet_posting--[#black]down>action_add_pet_posting
action_add_pet_posting..[#green]>show_pet_posting
action_add_pet_posting..[#red]>add_pet_posting

@enduml