@startuml profile
skinparam minClassWidth 100
skinparam classBackgroundColor WhiteSmoke
skinparam classBorderColor DarkSlateGrey
hide members
hide circles

class profile
class favourite_pets
class all_postings
class list_pets
class adoption_page
class adoption_proposals
class action_edit_username
class action_edit_password
class action_edit_image

profile<-[#black]up->action_edit_username
profile<-[#black]up->action_edit_password
profile<-[#black]up->action_edit_image
profile-[#black]down->favourite_pets
profile-[#black]down->all_postings
list_pets-[#black]down-o favourite_pets
list_pets-[#black]down-o all_postings
profile-[#black]down->adoption_proposals
adoption_page-[#black]down-o adoption_proposals

 
@enduml